services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-VerseEngine}
      - MONGODB_AUTH_SOURCE=${MONGODB_AUTH_SOURCE:-admin}
      - MONGODB_HOST=${MONGODB_HOST:-mongodb}
      - MONGODB_PORT=${MONGODB_PORT:-27017}
    depends_on:
      - mongodb
    restart: always